Update patch set 1
Patch Set 1: Verified+1 Code-Review+2

> Can't merge right now as it breaks nexus @dvd.
 > 
 > DataError: (pymysql.err.DataError) (1406, u"Data too long for
 > column 'subcategory' at row 70") [SQL: u'INSERT INTO report_checks
 > ...
 > 
 > Change is addimg:
 > 
 > "result": {
 > "out": "",
 > "err": "\n{'rc': 10, 'err': u'', 'plugin': '/core/pacemaker/nodes_number.sh'}\n{'rc':
 > 10, 'err': u'no failed actions detected', 'plugin':
 > '/core/pacemaker/failed_actions.sh'}\n{'rc': 20, 'err': u'NO
 > stonith devices configured', 'plugin': '/core/pacemaker/fence_device.sh'}\n...",
 > "rc": 10
 > },
 > "components": [
 > "3919f0b69e98e6053ea2dc1ec43318c4",
 > "f14232011067f7c626499a29efbd3999",
 > "1c8ecb3d34af7fc68210cfa42217a209"
 > ...
 > ],

I think this error was caused by something else.

Patch-set: 1
Reviewer: David Vallee Delisle <1012331@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=+2
Label: Verified=+1